spring.application.name=api-gateway
server.port=8180

spring.cloud.gateway.routes[0].id=note-service
spring.cloud.gateway.routes[0].uri=lb://note-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/notes/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.discovery.locator.enabled=true
spring.cloud.discovery.locator.lowerCaseServiceId=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.config.import=optional:configserver:http://localhost:8888



